### ISSUE TITLE
Specs not found in version 0.0.4

### ISSUE THREAD

**Issue by dgasull** [nuvlabox/mqtt-fiware-bridge#3]
Following error appears in version `nuvlabox/mqtt-fiware-bridge:0.0.4` : 
```
mqtt-to-dataclay_1  |     super(MQTTtoDataClayBridge, self).__init__(**kwargs)
mqtt-to-dataclay_1  |   File "/opt/nuvlabox/mqtt_fiware_bridge/MFB.py", line 50, in __init__
mqtt-to-dataclay_1  |     self.fiware_models = self.map_all_fiware_models(self.pkg_fiware_specs)
mqtt-to-dataclay_1  |   File "/opt/nuvlabox/mqtt_fiware_bridge/MFB.py", line 94, in map_all_fiware_models
mqtt-to-dataclay_1  |     listed_under = pkg_resources.resource_listdir(self.this_package_name, search_at)
mqtt-to-dataclay_1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1148, in resource_listdir
mqtt-to-dataclay_1  |     return get_provider(package_or_requirement).resource_listdir(
mqtt-to-dataclay_1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1426, in resource_listdir
mqtt-to-dataclay_1  |     return self._listdir(self._fn(self.module_path, resource_name))
mqtt-to-dataclay_1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1605, in _listdir
mqtt-to-dataclay_1  |     return os.listdir(path)
mqtt-to-dataclay_1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/nuvlabox/mqtt_fiware_bridge/fiware/specs'
```

If I go inside the image via `docker run -it --entrypoint /bin/sh nuvlabox/mqtt-fiware-bridge:0.0.4` and I type : 
```
# ls /opt/nuvlabox/mqtt_fiware_bridge/fiware/specs
ls: cannot access '/opt/nuvlabox/mqtt_fiware_bridge/fiware/specs': No such file or directory
```
However if go inside version 0.0.1 via `docker run -it --entrypoint /bin/sh nuvlabox/mqtt-fiware-bridge:0.0.4`: 
```
# ls /opt/nuvlabox/mqtt_fiware_bridge/fiware/specs
AgriFood     Building  Environment		Parking		    PointOfInterest  Transportation  WasteManagement  guidelines.md  index.md
Alert	     Device    IssueTracking		ParksAndGardens     README.md	     UrbanMobility   Weather	      howto.md	     ngsi-ld_faq.md
Aquaculture  Energy    KeyPerformanceIndicator	PointOfInteraction  StreetLighting   User	     gsma.md	      img	     ngsi-ld_howto.md
```

_Originally posted by @dgasull in https://github.com/nuvlabox/mqtt-fiware-bridge/issues/2#issuecomment-831920175_

**Comment by cjdcordeiro** [comment]
thanks for noticing that.

I've changed the CI engine and on the new one (Github actions), the fiware submodule was not being recursively pulled during the build.

Should be fixed now in tag 0.0.5. Please check again ;)

**Comment by daniwhere** [comment]
Still not working in version 0.0.5 :( 

```
 $ docker run -it --entrypoint /bin/sh nuvlabox/mqtt-fiware-bridge:0.0.5 
 ls /opt/nuvlabox/mqtt_fiware_bridge/fiware/specs
ls: cannot access '/opt/nuvlabox/mqtt_fiware_bridge/fiware/specs': No such file or directory
``` 

And: 

```
mqtt-to-dataclay_1  |   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1605, in _listdir
mqtt-to-dataclay_1  |     return os.listdir(path)
mqtt-to-dataclay_1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/nuvlabox/mqtt_fiware_bridge/fiware/specs'
```

Maybe it's because fiware specs changed? They've deprecated some files and created new standards one month ago.

**Comment by cjdcordeiro** [comment]
sorry, the tag was not up to date. should be fine now

**Comment by daniwhere** [comment]
it's working! ;) thanks!
